### ISSUE TITLE
"panic: assignment to entry in nil map" on startup

### ISSUE THREAD

**Issue by alanhughes** [hashicorp/consul-aws#15]
I'm running consul-aws on the same host that one of my consul masters is running on, and as soon as I execute the following command the application crashes:

```
$ consul-aws sync-catalog -aws-namespace-id <namespace-id> -to-aws -consul-service-prefix consul_ -http-addr http://<consul-ip-address>:8500
panic: assignment to entry in nil map

goroutine 38 [running]:
github.com/hashicorp/consul-aws/catalog.(*aws).create.func1(0xc0003317a0, 0xc0001f4000, 0xc000355ce0, 0x14, 0xc0003557a0, 0x1c, 0xc00036c6a0, 0xb, 0x7bca, 0xc00036c6a0, ...)
	/go-build/catalog/aws.go:366 +0x133
created by github.com/hashicorp/consul-aws/catalog.(*aws).create
	/go-build/catalog/aws.go:362 +0x3b1
```
This also happens when I run the command on a consul agent and point it to the local-ip address that the agent is advertised on.
Not sure what extra information I can give...we have no auth on our consul cluster and the EC2 instance has an IAM role with full permissions on Cloud Map. 

```
$ consul-aws version
consul-aws v0.1.1
```

**Comment by alanhughes** [comment]
Was running consul v1.0.3. Apologies, will update to 1.3 or 1.4 (compatible at time of writing) and try again.
